### ISSUE TITLE
Border bottom & text color is not changing on Active Menu using Tailwind CSS, React, & string interpolation

### ISSUE THREAD

**Issue by olifarhaan** [olifarhaan/griha-milan#1]
I have created a header menu on which I want to show the border-bottom of the red color & text-color of black on the active menu. To achieve this I am using the `useLocation()` function from the `react-router-dom` but it is not showing up.

This is the GitHub link of the repository: https://github.com/olifarhaan/griha-milan

### How to replicate the issue
1. Clone the repository on your local machine.
2. Run the following script `npm install`

![image](https://github.com/olifarhaan/griha-milan/assets/64217673/727c7bcc-c7fb-4e50-9e7e-06da88e575f6)

**Comment by IlmarsKuht** [comment]
Hey, I will check it out

**Comment by olifarhaan** [comment]
It has been fixed
